[env:esp32s3]
platform = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

board_build.flash_mode          = qio
board_build.flash_size          = 16MB
board_build.arduino.memory_type = qio_opi   ; ESP32-S3R8: OPI PSRAM + QIO flash

monitor_speed  = 115200
upload_speed    = 460800
upload_port     = COM3
monitor_port    = COM3
upload_protocol = esptool

lib_deps =
    moononournation/GFX Library for Arduino@1.5.6
    lvgl/lvgl@8.3.11
    PowerBroker2/ELMduino@^3.4.0

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -I include
    -DARDUINO_USB_CDC_ON_BOOT=0
    -std=gnu++17

build_unflags = -std=gnu++11

; Debug build – enable with: pio run -e debug
[env:debug]
extends    = env:esp32s3
build_flags =
    ${env:esp32s3.build_flags}
    -DCORE_DEBUG_LEVEL=4
    -DDEBUG_OBD
